[build]
  command = "npm run build"
  publish = "dist/public"

# Redirect /api calls to an external API host. Replace with your API origin.
[[redirects]]
  from = "/api/*"
  to = "https://ddrscamshield.netlify.app/:splat"
  status = 200
  force = true
